name: Prepare data used in subsequent jobs
description: Set up build matrix and check configuration
inputs:
  cloudsmithAPIKey:
    description:  Secret Cloudsmith API key
    required: false
outputs:
  GithubRegistryURL:
    description:  GitHub registry URL
    value: https://docker.pkg.github.com
  HasCloudsmithAPIKey:
    description: "If $CLOUDSMITH_API_KEY set, 'true', otherwise 'false'"
    value: ${{ steps.cloudsmith_checker.outputs.APIKeyPresent }}
  MainMatrix:
    description: The GitHub Actions job matrix
    value: ${{ steps.data_matrix_normalizer.outputs.matrix }}
  Timestamp:
    description: Timestamp of this run
    value: ${{ steps.timestamp_exporter.outputs.timestamp }}
runs:
  using: "composite"
  steps:
  - name: Show GitHub context as a JSON
    shell: bash {0}
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    run: |
      echo ::group::Show GitHub context
      echo "$GITHUB_CONTEXT"
      echo ::endgroup::

  - name: Prepare matrix from JSON
    id: data_matrix_normalizer
    shell: bash -e {0}
    run: |
      echo "matrix=$(querybuild github_main_matrix)" >> $GITHUB_OUTPUT
      echo ::group::Show main matrix
      querybuild --pretty --format yaml github_main_matrix
      echo ::endgroup::

  - name: Check for Cloudsmith API key in GitHub secrets storage
    id: cloudsmith_checker
    env:
      CLOUDSMITH_API_KEY: ${{ inputs.cloudsmithAPIKey }}
    shell: bash -e {0}
    run: |
      if ! [ -z "$CLOUDSMITH_API_KEY" ]
      then
        echo "Cloudsmith.io API key found; upload enabled"
        echo "APIKeyPresent=true">> $GITHUB_OUTPUT
      else
        echo "Cloudsmith.io API key not found; upload disabled"
        echo "APIKeyPresent=false" >> $GITHUB_OUTPUT
      fi

  - name: Export timestamp of workflow run in seconds since epoch
    id: timestamp_exporter
    shell: bash -e {0}
    run: |
      TIMESTAMP=$(date +%s)
      echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
      echo "Timestamp for this workflow run is $TIMESTAMP"
